// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9vTdI4MCI6gJs7B7nAu-COorCZAe5A_A',
    appId: '1:448526021399:android:2a25731f41630a2ecdfd52',
    messagingSenderId: '448526021399',
    projectId: 'reddit-clone-2f9ca',
    storageBucket: 'reddit-clone-2f9ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8lmQSNEWlxgYovK0Hcin7jjIDlFC3irY',
    appId: '1:448526021399:ios:78e93ed5664b5413cdfd52',
    messagingSenderId: '448526021399',
    projectId: 'reddit-clone-2f9ca',
    storageBucket: 'reddit-clone-2f9ca.appspot.com',
    androidClientId: '448526021399-2kn3p0qujhoohvlsuh0v3qbe1809u69a.apps.googleusercontent.com',
    iosClientId: '448526021399-u3nt671msjls68e6rafu2vqoblmr7evp.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApy3_zolvYzfrPpaxtJJZXXCPInfps6Ak',
    appId: '1:448526021399:web:d00ea687966c3124cdfd52',
    messagingSenderId: '448526021399',
    projectId: 'reddit-clone-2f9ca',
    authDomain: 'reddit-clone-2f9ca.firebaseapp.com',
    storageBucket: 'reddit-clone-2f9ca.appspot.com',
    measurementId: 'G-QXWFK5S45N',
  );

}